ExpressionPTT/models.py
# -*- coding: utf-8 -*-
# <standard imports>
from __future__ import division

import random
import decimal

import otree.models
from otree.db import models
from otree import widgets
from otree.common import Currency as c, currency_range, safe_json
import json
from otree.constants import BaseConstants
from otree.models import BaseSubsession, BaseGroup, BasePlayer
# </standard imports>

author = 'Your name here'

doc = """
Your app description
"""


class Constants(BaseConstants):
    name_in_url = 'ExpressionPTT'
    players_per_group = None
    num_rounds = 1


class Subsession(BaseSubsession):

    reader_message = models.TextField()
    debug_mode = models.BooleanField()
    vid_url = models.TextField()
    def before_session_starts(self):
        group_matrix = []
        empty_messages = []
        readers = max(self.session.config['readerSelection'])

        for reader in range(0, readers):
            empty_messages.append([])
            #  print(empty_messages)
            #  print(reader)
        self.reader_message = json.dumps(empty_messages)

        for grouping in self.session.config["group"]:
            print(grouping)
            # assigns groups based on array values in cofig
            group_matrix.append(grouping)

        self.set_group_matrix(group_matrix)
        self.debug_mode = self.session.config['debug']
        unparsed_video = self.session.config['video']
        vid_url = unparsed_video.split('v=')[1]

        i = 0
        for groupx in self.get_groups():
            groupx.treatment_endowment = self.session.config['endowment'][i]
            groupx.treatment_treatment = self.session.config['treatment'][i]
            groupx.target_income = self.session.config['targetIncome'][i]
            groupx.reader_index = self.session.config['readerSelection'][i]
            groupx.price_method = self.session.config['method'][i]
            for user in groupx.get_players():
                user.p_role = self.session.config['role'][i][user.id_in_group-1]
                # user.task_reward = user.participant.vars['task_income']
                # user.intermediate_reward = user.participant.vars['task_income'] + groupx.treatment_endowment

            if groupx.treatment_treatment == 'FM':
                groupx.b_eligible = True
                groupx.b_message_price = 0
            else:
                if self.session.config['price'][i] == -1: # -1 is encoding for random price
                    groupx.b_message_price = random.randrange(0, 300) / 100
                    # list vs cont only applies with WTP or WTA, not SOP
                    groupx.price_display = self.session.config['priceDisplay'][i]
                else:
                    groupx.b_message_price = self.session.config['price'][i]
            i += 1
        # message price is different (random) for every group
        print("finished set up before session starts")


class Group(BaseGroup):
    # variables that change for each group
    treatment_endowment = models.IntegerField()
    treatment_treatment = models.TextField()
    a_takes = models.DecimalField(min=0, max=100, max_digits=5, decimal_places=2)
    total_taken = models.CurrencyField()
    b_predicts = models.PositiveIntegerField(min=0, max=100)
    b_willing = models.DecimalField(min=0, max_digits=6, decimal_places=3)
    b_message = models.TextField()
    b_message_price = models.DecimalField(max_digits=5, decimal_places=2)
    price_method = models.TextField()
    price_display = models.TextField()
    b_eligible = models.BooleanField()
    target_income = models.DecimalField(max_digits=5, decimal_places=2)
    reader_index = models.IntegerField()

    def final_pay(self):
        p1 = self.get_player_by_id(1)
        p2 = self.get_player_by_id(2)
        p1.final_reward = self.treatment_endowment+ p1.task_reward + self.total_taken

        if self.price_method != 'WTA':
            if self.b_eligible:
                p2.final_reward = self.treatment_endowment+ p2.task_reward - self.total_taken - self.b_message_price
            else:
                p2.final_reward = self.treatment_endowment + p2.task_reward - self.total_taken
        else:  # WTA
            if self.b_eligible:
                p2.final_reward = self.treatment_endowment + p2.task_reward - self.total_taken
            else:  # gave up right to send message
                p2.final_reward = self.treatment_endowment + p2.task_reward - self.total_taken + self.b_message_price

    def reader_pay(self):
        for p in self.get_players():
            p.final_reward = self.treatment_endowment + p.task_reward


class Player(BasePlayer):
    # variables that change for each player
    task_reward = models.DecimalField(max_digits=5, decimal_places=2)
    intermediate_reward = models.DecimalField(max_digits=5, decimal_places=2)
    final_reward = models.DecimalField(max_digits=5, decimal_places=2)
    total_pay = models.DecimalField(max_digits=5, decimal_places=2)
    p_role = models.TextField()

    survey_response0 = models.IntegerField()
    survey_response1 = models.IntegerField()
    survey_response2 = models.IntegerField()
    survey_response3 = models.IntegerField()
    survey_response4 = models.IntegerField()
    survey_response5 = models.IntegerField()

    survey_responseA = models.IntegerField()
    survey_responseB = models.IntegerField()
    survey_responseC = models.IntegerField()
    survey_responseD = models.IntegerField()
    survey_responseE = models.IntegerField()
    survey_responseF = models.IntegerField()

    def get_partner(self):
        return self.get_others_in_group()[0]

ExpressionPTT/views.py
# -*- coding: utf-8 -*-
from __future__ import division

from otree.common import Currency as c, currency_range, safe_json

from . import models
from ._builtin import Page, WaitPage
from .models import Constants
import json
import random
from decimal import Decimal


class Part1Game (Page):
    form_model = models.Player
    form_fields = ['task_reward']

    def before_next_page(self):
        #self.participant.vars['task_income'] = self.player.task_reward
        print('got to before')
        if self.subsession.debug_mode:
            self.player.task_reward = random.uniform(1, 5)
        self.player.intermediate_reward = self.player.task_reward + self.group.treatment_endowment


class PracticeGame (Page):
    def is_displayed(self):
        return not self.subsession.debug_mode
    pass


class SurveyStart (Page):

    def is_displayed(self):
        return not self.subsession.debug_mode

    form_model = models.Player
    form_fields = ['survey_response0',
                   'survey_response1',
                   'survey_response2',
                   'survey_response3',
                   'survey_response4',
                   'survey_response5',
                   ]

    def before_next_page(self):
        print('got to player response')
        # print(self.player.survey_response)


class SurveyWaitPage (WaitPage):
    def is_displayed(self):
        return not self.subsession.debug_mode
    pass


class Part1 (Page):
    def before_next_page(self):
        self.player.task_reward = self.player.participant.vars['task_income']
        self.player.intermediate_reward = self.player.participant.vars['task_income'] + self.group.treatment_endowment



class Video(Page):
    def is_displayed(self):
        return not self.subsession.debug_mode
    pass


class Part1Result(Page):
    def is_displayed(self):
        return not self.subsession.debug_mode

    def vars_for_template(self):
        return {'reward': self.participant.vars['task_income'],
                'total': self.participant.vars['task_income'] + self.group.treatment_endowment}

    def before_next_page(self):
        self.player.task_reward = self.participant.vars['task_income']



class Part1Wait(WaitPage):
    pass


class Part2 (Page):
    def is_displayed(self):
        return not self.subsession.debug_mode
    pass


class Roles (Page):
    def is_displayed(self):
        return not self.player.p_role == "R"

    def vars_for_template(self):
        return {
            'partner': self.player.get_partner()
        }


class TakeA(Page):

    form_model = models.Group
    form_fields = ['a_takes']

    def is_displayed(self):
        return self.player.p_role == 'A'  # and not self.player.p_role == "R"

    def vars_for_template(self):
        return {
            'partner': self.player.get_partner()
        }

    def before_next_page(self):
        self.group.a_takes *= Decimal(.01)


class TakeWaitPage(WaitPage):

    pass


class PredictB(Page):
    form_model = models.Group
    form_fields = ['b_predicts']

    def is_displayed(self):
        return self.player.p_role == 'B'

    def vars_for_template(self):
        return {
            'partner': self.player.get_partner()
        }

    def before_next_page(self):
        self.group.total_taken = self.player.task_reward * self.group.a_takes


class WillingnessB(Page):
    def is_displayed(self):
        return self.group.price_display == 'CONT' and self.player.p_role == 'B' and (self.group.treatment_treatment == 'DM' or self.group.treatment_treatment == 'TP')

    form_model = models.Group
    form_fields = ['b_willing']

    def b_willing_max(self):
        if self.group.price_method == "WTA":
            return 100
        return self.player.task_reward - self.player.task_reward * self.group.a_takes

    def vars_for_template(self):
        return {
            'a_takes_edited': self.group.a_takes * 100,
            'partner': self.player.get_partner(),
            'taken_amount': round(self.player.task_reward * self.group.a_takes, 2),
            'available_earnings': round(self.player.task_reward - self.player.task_reward * self.group.a_takes, 2)
        }

    def before_next_page(self):
        if self.group.b_message_price <= self.group.b_willing and self.group.price_method == 'WTP':
            self.group.b_eligible = True
        else:
            self.group.b_eligible = False
        #  if they give you more than you ask for, you lose your message and get the money
        if self.group.b_message_price <= self.group.b_willing and self.group.price_method == 'WTA':  # will lose right to send message
            self.group.b_eligible = True
        else:
            self.group.b_eligible = False

        if self.subsession.debug_mode and self.group.price_method != 'WTA':
            self.group.b_eligible = True


class WillingnessBList(Page):
    def is_displayed(self):
        return self.group.price_display == 'LIST' and self.player.p_role == 'B' and (self.group.treatment_treatment == 'DM' or self.group.treatment_treatment == 'TP')

    form_model = models.Group
    form_fields = ['b_willing']

    def b_willing_choices(self):
        available = round(self.player.task_reward - (self.player.task_reward * self.group.a_takes), 1)
        if self.group.price_method == 'WTA':
            return [x * 0.5 for x in range(0, 10 + 1, 15)]
        if self.group.price_method == 'WTP':
            print(available)
            new_available = int(available * 100)
            print(new_available)
            # return [x * 0.5 for x in range(0, 10 + 1)]
            return_values = [float(format(x * .01, '.2f')) for x in range(0, new_available, 10)]
            # return_values = [Decimal(round(x * .01, 1)) for x in range(0, new_available, 10)]
            print(return_values)
            return return_values
            # return range(0, self.player.task_reward, 1)

    def b_willing_max(self):
        if self.group.price_method == "WTA":
            return 100
        return self.player.task_reward - self.player.task_reward * self.group.a_takes

    def vars_for_template(self):
        return {
            'a_takes_edited': self.group.a_takes * 100,
            'partner': self.player.get_partner(),
            'taken_amount': round(self.player.task_reward * self.group.a_takes, 2),
            'available_earnings': round(self.player.task_reward - self.player.task_reward * self.group.a_takes, 2)
        }

    def before_next_page(self):
        if self.group.b_message_price <= self.group.b_willing and self.group.price_method == 'WTP':
            self.group.b_eligible = True
        else:
            self.group.b_eligible = False
        #  if they give you more than you ask for, you lose your message and get the money
        if self.group.b_message_price <= self.group.b_willing and self.group.price_method == 'WTA':  # will lose right to send message
            self.group.b_eligible = True
        else:
            self.group.b_eligible = False

        if self.subsession.debug_mode and self.group.price_method != 'WTA':
            self.group.b_eligible = True


class SendMessage(Page):
    form_model = models.Group
    form_fields = ['b_message']

    def is_displayed(self):
        return (self.group.b_eligible and (
            self.group.treatment_treatment == 'DM' or self.group.treatment_treatment == 'TP') or self.group.treatment_treatment == 'FM') and self.player.p_role == 'B'

    # add message to list of reader messages
    def before_next_page(self):
        jsonDec = json.decoder.JSONDecoder()
        messages_list = jsonDec.decode(self.subsession.reader_message)
        print(messages_list)
        reader = self.group.reader_index - 1

        messages_list[reader].append(self.group.b_message)
        print(messages_list)
        print(messages_list[reader])
        self.subsession.reader_message = json.dumps(messages_list)
        print(self.subsession.reader_message)


class WaitForMessage(WaitPage):
    def is_displayed(self):
        return not self.group.treatment_treatment == 'TP'
    pass


class WaitForManyMessage(WaitPage):
    def is_displayed(self):
        return self.group.treatment_treatment == 'TP' or self.group.treatment_treatment == 'TPE'
    wait_for_all_groups = True
    pass


class ReaderManyMessages(Page):
    def is_displayed(self):
        return (self.group.treatment_treatment == 'TP' or self.group.treatment_treatment == 'TPE') \
               and self.player.p_role == "R"

    def vars_for_template(self):
        jsonDec = json.decoder.JSONDecoder()
        messages_list = jsonDec.decode(self.subsession.reader_message)
        return {
            'messages': messages_list[self.player.id_in_group - 1],
            'allMessages': messages_list
        }


class DisplayMessage(Page):
    def is_displayed(self):
        play = self.player
        group = self.group
        # play.total_pay = play.intermediate_reward + play.task_reward * self.group.a_takes
        return play.p_role == 'A' and (
            group.treatment_treatment == 'DM' or group.treatment_treatment == 'FM') or (
            play.p_role == 'R' and group.treatment_treatment == 'TP')

    def before_next_page(self):
        self.player.total_pay = self.group.treatment_endowment + self.player.task_reward + self.group.total_taken


class MessageReadWait(WaitPage):
    pass


class MessageRead(Page):

    def is_displayed(self):
        # old
        # return self.player.p_role == 'B' and (
        #     self.group.treatment_treatment == 'DM' or self.group.treatment_treatment == 'FM' or self.group.treatment_treatment == 'TP')
        # new
        return self.player.p_role == 'B' and (self.group.b_eligible and (
            self.group.treatment_treatment == 'DM' or self.group.treatment_treatment == 'TP') or self.group.treatment_treatment == 'FM')


    def before_next_page(self):
        self.group.final_pay()


class ResultsWaitPage(WaitPage):

    def after_all_players_arrive(self):

ExpressionPTT/templates/ExpressionPTT/DisplayMessage.html
{% extends "global/Base.html" %} {% load staticfiles otree_tags %}

{% block title %} Display Message{% endblock %}

{% block content %}

{% if group.b_message == null or group.b_message == Null %}
<p>Unfortunately, your counterpart was unable to send a message.</p>
{% else %}
    <p>The following is a message from your counterpart</p>
    <p>"{{group.b_message}}"</p>
{% endif %}
    {% next_button %}

{% endblock %}

ExpressionPTT/templates/ExpressionPTT/Part1.html
{% extends "global/Base.html" %} {% load staticfiles otree_tags %}

{% block title %} Part 1 {% endblock %}

{% block scripts %}
<script type="text/javascript">
jQuery(document).ready(function ($) {
   var target = $('#target').val();
    console.log(target);

});

</script>


{% endblock %}


{% block content %}

<p>
You are ready to begin part 1.
</p>

{% if subsession.debug_mode == True %}
<p>{{group.treatment_endowment}}</p>
<p>{{group.treatment_treatment}}</p>
<p>{{player.p_role}}</p>
<p>{{group.b_message_price}}</p>
<p>{{group.price_display}}</p>
<p>{{group.price_method}}</p>
<p>{{subsession.vid_url}}</p>
<input id = 'target'  type = "number" value = {{group.target_income}} style = 'display: none;'>
<p>Debug mode is on, turn off in Settings.py</p>
{% endif %}

{% next_button %}

{% endblock %}

ExpressionPTT/templates/ExpressionPTT/Part1Result.html
{% extends "global/Base.html" %} {% load staticfiles otree_tags %}

{% block title %} Part 1 Result{% endblock %}

{% block content %}

<p>
    In this experiment, you have received {{group.treatment_endowment}} endowment and earned ${{player.task_reward}} for a total of {{player.intermediate_reward}}
</p>

{% next_button %}

{% endblock %}

ExpressionPTT/templates/ExpressionPTT/PredictB.html
{% extends "global/Base.html" %} {% load staticfiles otree_tags %}

{% block title %} B predicts{% endblock %}

{% block styles %}
<link href="{% static "jquery-ui/jquery-ui.min.css" %}" rel="stylesheet">
<style type="text/css">
    .bid-slider {
        margin: .5em auto;
    }

    .bid {
        text-align: center;
    }
    .textlabel{
        border:0;
        color:#f6931f;
        font-weight:bold;
    }

    .payoff {
        margin: 1.5em 0;
    }
</style>
{% endblock %}

{% block scripts%}
<script type="text/javascript" src="{% static "jquery-ui/jquery-ui.min.js" %}"></script>

<script type="text/javascript">
jQuery(document).ready(function ($) {

//    var input;// = $('#id_slide1text');

        $('#id_slide1text').val(null);
        $('#slide1text').val(null);

        $("#slide1").slider({
          orientation: "horizontal",
          max: 100,min: 0,
            value: -1,
          slide: function (event, ui){
              var tempName = this.id;
              $('#id_'+ tempName + 'text').val(ui.value);
              ui.handle.style.display = "inline";
              console.log(tempName);
              $('#'+ tempName + "text").val(ui.value);
              updateValues(tempName);
              checkValid(tempName);
          }
        });

    function checkValid(){
        var myVal = $('#id_slide1text').val() ;
        console.log(myVal);
        if( !myVal){
            $("#hideNext").hide();
            return
        } else{
            $("#hideNext").show();
        }
    };

    $(".ui-slider-handle").hide();
    $("#hideNext").hide();


    function updateValues(name) {
        $('.' + name ).text($("#" + name + 'text').val());
    };
});

</script>
{% endblock%}

{% block content %}
    <p>
        At this moment, your counterpart A is deciding what proportion of your income (${{player.task_reward}}) to transfer to his/her own account.
    </p>
    <p>
    What percentage of your income do you think A will transfer into their Account?
    </p>

<div class="form-group required">
        <div class="controls">
            <div class="row">
                <div class="col-md-1" ></div>
                <div class="col-md-10" id="slide1"></div>
                <input type="hidden" name="b_predicts" id="id_slide1text" value="0">
                <div class="col-md-1"><span class="slide1"  type="hidden" id="slide1text" readonly ></span>%</div>
            </div>
        </div>
    </div>

<div id="hideNext">
{% next_button %}
</div>



{% endblock %}

ExpressionPTT/templates/ExpressionPTT/ReaderManyMessages.html
{% extends "global/Base.html" %} {% load staticfiles otree_tags %}

{% block title %} Reader Many messages{% endblock %}

{% block content %}

{% for message in messages  %}
  <p>"{{ message}}"</p>
{% endfor %}

{% next_button %}

{% endblock %}

ExpressionPTT/templates/ExpressionPTT/Results.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Results/ Earnings
{% endblock %}

{% block styles %}
<style type="text/css">
    .table_wrap{
margin-right:200px;
    }
</style>
{% endblock %}


{% block content %}
{% if player.id_in_group == 1 %}
      <div class="container table_wrap">
    <h2 class="text-center">
      Earnings (in $)</h3>
    </h2>
    <br>
    <div class="row table_wrap">
      <table class="table table-striped table-bordered table-nonfluid" align="center">
        <tr>
          <td class="col-md-1"></td>
          <td class="col-md-1 text-center">Role A (You)</td>
          <td class="col-md-1 text-center">Role B </td>
        </tr>
        <tr >
          <td>Endowment</td>
          <td class="text-center">{{group.treatment_endowment }}</td>
          <td class="text-center">{{group.treatment_endowment}}</td>
        </tr>
        <tr>
          <td>Income</td>
          <td class="text-center">{{player.task_reward}}</td>
          <td class="text-center">{{partner.task_reward}}</td>
        </tr>
        <tr>
          <td>Money Transferred</td>
          <td class="text-center">+{{group.total_taken}}</td>
          <td class="text-center">-{{group.total_taken}}</td>
        </tr>
        <tr >
          <td>Message Price</td>
          <td class="text-center">None</td>
          <td class="text-center">{{group.b_message_price}}</td>
        </tr>
        <tr>
          <td>Total Earnings</td>
          <td class="text-center">{{player.final_reward}}</td>
          <td class="text-center">{{partner.final_reward}}</td>
        </tr>
      </table>
    </div>
  </div>
{% elif player.id_in_group == 2 %}
      <div class="container">
    <h2 class="text-center">
      Earnings (in $)</h3>
    </h2>
    <br>
    <div class="row table_wrap">
      <table class="table table-striped table-bordered table-nonfluid" align="center">
        <tr>
          <td class="col-md-1"></td>
          <td class="col-md-1 text-center" >Role A</td>
          <td class="col-md-1 text-center">Role B (You)</td>
        </tr>
        <tr >
          <td>Endowment</td>
          <td class="text-center">{{group.treatment_endowment }}</td>
          <td class="text-center">{{group.treatment_endowment }}</td>
        </tr>
        <tr>
          <td>Income</td>
          <td class="text-center">{{partner.task_reward}}</td>
          <td class="text-center">{{player.task_reward}}</td>
        </tr>
        <tr>
          <td>Money Transferred</td>
          <td class="text-center">+{{group.total_taken}}</td>
          <td class="text-center">-{{group.total_taken}}</td>
        </tr>
        <tr >
          <td>Message Price</td>
          <td class="text-center">None</td>
          <td class="text-center">{{group.b_message_price}}</td>
        </tr>
        <tr>
          <td>Total Earnings</td>
          <td class="text-center">{{partner.final_reward}}</td>
          <td class="text-center">{{player.final_reward}}</td>
        </tr>
      </table>
    </div>
  </div>

{% else %}

<p>You are neither player A nor B. Instead, you are a reader.</p>
{% endif %}







    {% next_button %}
{% endblock %}

ExpressionPTT/templates/ExpressionPTT/SendMessage.html
{% extends "global/Base.html" %} {% load staticfiles otree_tags %}

{% block title %} Message Box{% endblock %}



{% block scripts %}
<script type="text/javascript" src="{% static "vickrey_auction/jquery-ui/jquery-ui.min.js" %}"></script>
<script type="text/javascript">
jQuery(document).ready(function ($) {

    var input = $('#id_b_message');
    input.text("");

    var hello = function(){
        if(input.val() != ""){
            $("#hideNext").show();
        } else {
            $("#hideNext").hide();
        }

    }

    $("textarea").on({
        mouseenter: hello,
        mouseleave: hello,
        click: hello,
        blur: hello,
        keyup: hello
    });


    $("#hideNext").hide();

});
</script>
{% endblock %}


{% block content %}

{% if group.price_method == "WTA" %}
<p>You requested too much money. You can still send a message.</p>
{% endif %}

{% formfield group.b_message with label="Write a message here" %}

{% next_button %}
<div id="hideNext" style="display: none;">

</div>
{% endblock %}

ExpressionPTT/templates/ExpressionPTT/TakeA.html
{% extends "global/Base.html" %} {% load staticfiles otree_tags %}

{% block title %} A takes{% endblock %}

{% block styles %}
<link href="{% static "jquery-ui/jquery-ui.min.css" %}" rel="stylesheet">
<style type="text/css">
    .bid-slider {
        margin: .5em auto;
    }

    .bid {
        text-align: center;
    }
    .textlabel{
        border:0;
        color:#f6931f;
        font-weight:bold;
    }

    .payoff {
        margin: 1.5em 0;
    }
</style>
{% endblock %}

{% block scripts %}

<script type="text/javascript" src="{% static "jquery-ui/jquery-ui.min.js" %}"></script>

<script type="text/javascript">
jQuery(document).ready(function ($) {

//    var input;// = $('#id_slide1text');

        $('#id_slide1text').val(null);
        $('#slide1text').val(null);

        $("#slide1").slider({
          orientation: "horizontal",
          max: 100,min: 0,
            value: -1,
          slide: function (event, ui){
              var tempName = this.id;
              $('#id_'+ tempName + 'text').val(ui.value);
              ui.handle.style.display = "inline";
              console.log(tempName);
              $('#'+ tempName + "text").val(ui.value);
              updateValues(tempName);
              checkValid(tempName);
          }
        });

    function checkValid(){
        var myVal = $('#id_slide1text').val() ;
        console.log(myVal);
        if( !myVal){
            $("#hideNext").hide();
            return
        } else{
            $("#hideNext").show();
        }
    };

    $(".ui-slider-handle").hide();
    $("#hideNext").hide();


    function updateValues(name) {
        $('.' + name ).text($("#" + name + 'text').val());
    };
});

</script>
{% endblock %}

{% block content %}

    <p>
        Being A, you are given the authority to transfer money from B's account to your own account. The maximum amount
        of money you can collect is what B has earned as income in Part 1 (${{partner.task_reward}}).
    </p>
    <p>
    What percentage of B's income do you want to transfer to your account?
    (Use the slider below to set this percentage)
    </p>

    <div class="form-group required">
        <div class="controls">
            <div class="row">
                <div class="col-md-1" ></div>
                <div class="col-md-10" id="slide1"></div>
                <input type="hidden" name="a_takes" id="id_slide1text" value="0">
                <div class="col-md-1"><span class="slide1"  type="hidden" id="slide1text" readonly ></span>%</div>
            </div>
        </div>
    </div>

<div id="hideNext">
{% next_button %}
</div>
{% endblock %}

ExpressionPTT/templates/ExpressionPTT/Video.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Instruction Video
{% endblock %}

{% block content %}
  <h3 class="text-center">A Video will be displayed here</h3>

  <div class="text-center">
    <iframe width="420" height="345" src="https://www.youtube.com/embed/YgdR5FvnNPc">
      </iframe>

  </div>


    {% next_button %}
{% endblock %}

ExpressionPTT/templates/ExpressionPTT/WillingnessB.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Willingness
{% endblock %}

{% block content %}

<p>

    Your counterpart, A, has transferred {{a_takes_edited}}% of your income (${{taken_amount}}) to their own account.
Your available earnings are now ${{available_earnings}}
</p>
{% if group.price_method == "WTP" %}

<p>
    What is the maximum amount you would be willing to pay to write and send a message that your counterpart A will read?
</p>

<p>
    (Express the amount in dollars and cents)
</p>

    {% formfield group.b_willing with label="How much will you pay?" %}

{% elif group.price_method == "WTA" %}
<p>
    You are eligible to send a message to your counterpart. How much money would you want to receive in exchange for giving up your right to send a message?
</p>

<p>
    (Express the amount in dollars and cents)
</p>

    {% formfield group.b_willing with label="How much do you expect?" %}


{% endif %}

<p>The actual price of sending a message will be shown on the next screen.</p>
    {% next_button %}
{% endblock %}

ExpressionPTT/templates/ExpressionPTT/WillingnessBList.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Willingness List
{% endblock %}

{% block scripts%}

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	var PHONES = new Array("Sony","Samsung","HTC","Motorolla");
	var available = 5.5;
	$("#dropdown").find('option').remove();
	//for(i=0; i < PHONES.length; i++){
	for(i=0; i < 5.5; i+=.20){
		var rounded = Math.round(i * 100) / 100
		$("#dropdown").append('<option value="'+rounded+'">'+rounded+'</option>');
	}
});
</script>
{% endblock %}

{% block content %}

<p>

    Your counterpart, A, has transferred {{a_takes_edited}}% of your income (${{taken_amount}}) to their own account.
Your available earnings are now ${{available_earnings}}
</p>




<p>
    What is the maximum amount you would be willing to pay to write and send a message that your counterpart A will read?
</p>

<p>
    (Express the amount in dollars and cents)
</p>

<select id="dropdown"></select>
    {% formfield group.b_willing with label="How much will you pay?" %}


<p>The actual price of sending a message will be shown on the next screen.</p>
    {% next_button %}
{% endblock %}